# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 10

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = ['workspace Code', 'layout accordion vertical'] # code
alt-2 = ['workspace Browser', 'layout accordion vertical'] # browser
alt-3 = 'workspace Tradester' # tradester
alt-4 = 'workspace TPH' # tph
alt-5 = 'workspace Me' # personal

alt-q = ['workspace Trading2', 'workspace Trading'] # trading
alt-w = ['workspace Trading', 'workspace Trading2'] # trading2
alt-e = ['workspace Other', 'layout accordion vertical'] # other
alt-r = ['workspace Util', 'layout accordion vertical'] # util
alt-t = 'workspace Term' # terminal

alt-f = 'fullscreen' 

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = ['move-node-to-workspace Code', 'workspace Code']
alt-shift-2 = ['move-node-to-workspace Browser', 'workspace Browser']
alt-shift-3 = ['move-node-to-workspace Tradester', 'workspace Tradester']
alt-shift-4 = ['move-node-to-workspace TPH', 'workspace TPH']
alt-shift-5 = ['move-node-to-workspace Me', 'workspace Me']


alt-shift-q = ['move-node-to-workspace Trading', 'workspace Trading']
alt-shift-w = ['move-node-to-workspace Trading2', 'workspace Trading2']
alt-shift-e = ['move-node-to-workspace Other', 'workspace Other']
alt-shift-r = ['move-node-to-workspace Util', 'workspace Util']
alt-shift-t = ['move-node-to-workspace Term', 'workspace Term']


# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth`
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-enter = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
# e = ['disable', 'mode main']
q = ['close-all-windows-but-current', 'mode main']
r = ['close-all-windows-but-current', 'fullscreen', 'mode main']
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']



# force workspace assignment
[workspace-to-monitor-force-assignment]
Code = "^Portable \\(2\\)$"
Trading = "^Portable \\(2\\)$"
Browser = "^Portable \\(1\\)$"
Trading2 = "^Portable \\(1\\)$"
Tradester = "^Portable \\(1\\)$"
TPH = "^Portable \\(1\\)$"
Me = "Sidecar Display"


# app detections
[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser' # arc browser 
run = "move-node-to-workspace Browser"

[[on-window-detected]]
if.app-id = 'com.googlecode.iterm2' # iterm2 
run = "move-node-to-workspace Term"

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92' # cursor 
run = ["move-node-to-workspace Code"]

[[on-window-detected]]
if.app-id = 'com.apple.finder' #finder 
run = "move-node-to-workspace Find"

[[on-window-detected]]  
if.app-id = 'com.nordsec.nordpass' # nordpass 
run = "move-node-to-workspace Util"

[[on-window-detected]]
if.app-id = 'com.authy' # authy 
run = "move-node-to-workspace Util"



# window detections
# 




